### ISSUE TITLE
Steps to try this Flask Webapp

### ISSUE THREAD

**Issue by iamShantanu101** [luisvalesilva/digitre#1]
Hey,

Can you create a file which will just walk us through how to try this app locally?

**Comment by luisvalesilva** [comment]
Hi,
Just added instructions to README.md. This should do it.

**Comment by iamShantanu101** [comment]
Are you sure older version of tensorflow works correctly? I got this error:

`ImportError: No module named 'tensorflow.contrib.rnn.python.ops.core_rnn'`

**Comment by luisvalesilva** [comment]
TensorFlow version 0.11 worked for me in both Mac OS X El Capitan and Ubuntu 16.04.2 LTS. 

TensorFlow 1.0 is now out, so you could try that. They do say the APIs have changed in ways that are [not all backwards compatible](https://www.tensorflow.org/install/migration), though. You could also drop TFLearn and try TensorFlow directly.

**Comment by iamShantanu101** [comment]
That was fixed when I upgraded tensorflow, but what I observed is that I had to first train the model and then run:

`python digitre/digitre.py`

If I try to the above command directly according to your README, then it throws an error:

```
NotFoundError (see above for traceback): Tensor name "Adam/Total_Loss/moving_avg" not found in checkpoint files /Users/shantanudeshpande/thefuck/digitre/digitre/cnn.tflearn
	 [[Node: save_1/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_1/tensor_names, save_1/RestoreV2_1/shape_and_slices)]]
```

**Comment by luisvalesilva** [comment]
I see. This has worked for me in two machines running Mac OS X and two running Ubuntu, so I believe these instructions are accurate.

So you have it working now, after having retrained the model?

**Comment by iamShantanu101** [comment]
I tried this on MacOS. Now I have it working. I think maybe it was not able to find the classifier cnn.tflearn.

**Comment by luisvalesilva** [comment]
Ok, happy to hear. I will close the issue, then.

**Comment by iamShantanu101** [comment]
Hey, whats this error:
File "/usr/local/lib/python3.4/dist-packages/tflearn/layers/conv.py", line 75, in <lambda>
    W_regul = lambda x: losses.get(regularizer)(x, weight_decay)
  File "/usr/local/lib/python3.4/dist-packages/tflearn/losses.py", line 29, in L2
    return tf.mul(tf.nn.l2_loss(tensor), wd, name='L2-Loss')
AttributeError: 'module' object has no attribute 'mul'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "digitre_model.py", line 199, in <module>
    main()
  File "digitre_model.py", line 158, in main
    model = build()
  File "digitre_model.py", line 79, in build
    cnn = conv_2d(cnn, 32, 5, activation='relu', regularizer="L2")
  File "/usr/local/lib/python3.4/dist-packages/tflearn/layers/conv.py", line 78, in conv_2d
    trainable=trainable, restore=restore)
  File "/usr/local/lib/python3.4/dist-packages/tflearn/variables.py", line 54, in variable
    collections=collections)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/variable_scope.py", line 988, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/variable_scope.py", line 890, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/variable_scope.py", line 348, in get_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/variable_scope.py", line 333, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/variable_scope.py", line 639, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable Conv2D/W already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "/usr/local/lib/python3.4/dist-packages/tflearn/variables.py", line 48, in variable
    collections=collections)
  File "/usr/local/lib/python3.4/dist-packages/tflearn/layers/conv.py", line 78, in conv_2d
    trainable=trainable, restore=restore)
  File "digitre_model.py", line 79, in build
    cnn = conv_2d(cnn, 32, 5, activation='relu', regularizer="L2")
